### ISSUE TITLE
Accept GATK output VCF files?

### ISSUE THREAD

**Issue by danagibbon** [Magdoll/CoSA#11]
Hello,

Is it possible to get this tool to work with a VCF file that was output from GATK?

Thanks,
Dana

**Comment by Magdoll** [comment]
Hi @danagibbon ,
I believe GATK follows the standard VCF format that DeepVariant also uses.
You can run it with `--vcf_type deepvariant`. If breakage occurs, please let me know and I can add GATK support!
-Liz

**Comment by danagibbon** [comment]
Thanks, Liz. That worked!
